id: A3D60BD83
title: 'A Yogi’s Song of Happiness: The Melody that Brings Universal Auspiciousness
  and Fulfilment'
type: translation
pechas:
- I5349CD66
- IEAB1A8B4
- I29BF6D99
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:50:30.886462
  last_modified_at: 2023-01-04 12:50:30.886480
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I5349CD66/8049: '5995'
  IEAB1A8B4/7F42: '5995'
  I29BF6D99/69FC: '5995'
